function fltool(varargin)
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

frac_version = '2.03';

%[logo_frac cmap_frac]=imread('logo_trans.gif');
[logo_frac cmap_frac alpha_frac]=fl_getOption('Logo');
%[logo_frac cmap_frac]=imread('logo_frac.tif');
%[logo_frac cmap_frac]=imread('etoile_floue.gif');
%[logo_frac cmap_frac]=imread('nenuphares.gif');
%[logo_frac cmap_frac]=imread('plancton.gif');
%[logo_frac cmap_frac]=imread('raie.gif');
%[logo_frac cmap_frac]=imread('emelle.gif');
%[logo_frac cmap_frac]=imread('rosace.gif');
%[logo_frac cmap_frac]=imread('spin_space.gif');

[bg_frac bg_cmap_frac]= fl_getOption('BackGround');


%frac_color=[0.2 0.4 1];
%frac_color=[rand(1), rand(1),rand(1)];
%frac_color2=[rand(1), rand(1),rand(1)];

%frac_color=[0.6906    0.9610    0.7755];
%frac_color2=[0.0007    0.3255    0.5441];

frac_color=fl_getOption('FrameColor');
frac_color2=fl_getOption('ButtonColor');


switch(fl_getOption('Layout'))
case 1
	%LayoutHonrizontal
	LogoAxesPosition = [0.05 0.8 0.90 0.1725];
	MainFramePosition = [0.0390625 0.227045075125209 0.91796875 0.550918196994992];
	ImportFramePosition  = [0.511953125 0.247078464106845 0.4140625 0.120200333889816];
	ImportFrameTextPosition  = [0.58421875 0.318864774624374 0.26953125 0.0300500834724541];
	VariableFramePosition = [0.073984375 0.247078464106845 0.4140625 0.120200333889816];
	VariableFrameTextPosition = [0.14625 0.318864774624374 0.26953125 0.0300500834724541];
	MessageFramePosition = [0.0390625 0.118530884808013 0.919921875 0.10016694490818];
	ActionsFramePosition = [0.037109375 0.0217028380634391 0.919921875 0.0868113522537563];
	VariablesListboxPosition = [0.111328125 0.387312186978297 0.359375 0.320534223706177];
	VariablesTextPosition = [0.228515625 0.719532554257095 0.126953125 0.0317195325542571];
	DetailsListboxPosition = [0.53125 0.387312186978297 0.35546875 0.320534223706177];
	DetailsTextPosition = [0.646484375 0.719532554257095 0.126953125 0.0317195325542571];
	ViewButtonPosition = [0.10328125 0.265442404006678 0.1015625 0.0400667779632721];
	ClearButtonPosition = [0.226328125 0.265442404006678 0.109375 0.0400667779632721];
	SaveButtonPosition = [0.355234375 0.265442404006678 0.10546875 0.0400667779632721];
	FileButtonPosition = [0.547109375 0.265442404006678 0.162109375 0.0400667779632721];
	WorkspaceButtonPosition = [0.744375 0.265442404006678 0.150390625 0.0400667779632721];
	MessageTextPosition = [0.076171875 0.145258764607679 0.11546875 0.0287111853088481];
	MessageEditPosition = [0.1953125 0.146911519198664 0.6171875 0.0350584307178631];
	EraseButtonPosition = [0.830078125 0.146911519198664 0.099609375 0.0400667779632721];
	CustomizeButtonPosition = [0.060546875 0.0400667779632721 0.1875 0.0534223706176962];
	HelpButtonPosition = [0.28859375 0.0400667779632721 0.1875 0.0534223706176962];
	DemosButtonPosition = [0.5178125 0.0400667779632721 0.1875 0.0534223706176962];
	QuitButtonPosition = [0.751953125 0.0400667779632721 0.1875 0.0534223706176962];
	DetailsTextBackgroundColor = frac_color;
	VariablesTextBackgroundColor = frac_color;
	MessageTextBackgroundColor = frac_color;
	DetailsTextForegroundColor = frac_color;
    FileText = 'File';

case 2
	%LayoutVertical 1
	LogoAxesPosition = [0.02375 0.0433333333333333 0.1725 0.901666666666667];
	MainFramePosition = [0.21875 0.226666666666667 0.7675 0.751666666666667];
	ImportFramePosition  = [0.61375 0.246666666666667 0.35125 0.13];
	ImportFrameTextPosition  = [0.65375 0.328333333333333 0.27 0.03];
	VariableFramePosition = [0.23875 0.246666666666667 0.35125 0.13];
	VariableFrameTextPosition = [0.27875 0.328333333333333 0.27 0.03];
	DetailsListboxPosition = [0.62375 0.413333333333333 0.33 0.466666666666667];
	DetailsTextPosition = [0.725 0.913333333333334 0.1275 0.0316666666666667];
	MessageFramePosition = [0.2190625 0.118530884808013 0.769921875 0.10016694490818];
	ActionsFramePosition = [0.217109375 0.0217028380634391 0.769921875 0.0868113522537563];
	VariablesListboxPosition = [0.25125 0.413333333333333 0.325 0.47];
	VariablesTextPosition = [0.35 0.913333333333334 0.1275 0.0316666666666667];
	ViewButtonPosition = [0.25375 0.265 0.09 0.04];
	ClearButtonPosition = [0.36875 0.265 0.09 0.04];
	SaveButtonPosition = [0.485 0.265 0.09 0.04];
	FileButtonPosition = [0.63375 0.265 0.1475 0.04];
	WorkspaceButtonPosition = [0.8075 0.265 0.13375 0.04];
	MessageTextPosition = [0.2525 0.155 0.08125 0.0266666666666667];
	MessageEditPosition = [0.3475 0.146666666666667 0.4975 0.0366666666666667];
	EraseButtonPosition = [0.86375 0.146666666666667 0.1 0.04];
	CustomizeButtonPosition = [0.24625 0.038 0.15375 0.0516666666666667];
	HelpButtonPosition = [0.43 0.038 0.15375 0.0516666666666667];
	DemosButtonPosition = [0.61625 0.038 0.15375 0.0516666666666667];
	QuitButtonPosition = [0.80625 0.038 0.15375 0.0516666666666667];
	DetailsTextBackgroundColor = frac_color;
	VariablesTextBackgroundColor = frac_color;
	MessageTextBackgroundColor = frac_color;
    FileText = 'File';    
	
case 3
	%LayoutVertical 2
	LogoAxesPosition = [0.02375 0.0433333333333333 0.1725 0.901666666666667];
	MainFramePosition = [0.218781218781219 0.152097902097902 0.615384615384615 0.825174825174825];
	ImportFramePosition  = [0.534465534465534 0.190559440559441 0.28971028971029 0.129370629370629];
	ImportFrameTextPosition  = [0.544455544455544 0.277972027972028 0.26973026973027 0.0297202797202797];
	VariableFramePosition = [0.232767232767233 0.190559440559441 0.28971028971029 0.129370629370629];
	VariableFrameTextPosition = [0.242757242757243 0.277972027972028 0.26973026973027 0.0297202797202797];
	DetailsListboxPosition = [0.542457542457542 0.368881118881119 0.274725274725275 0.5];
	DetailsTextPosition = [0.615384615384615 0.902097902097902 0.127872127872128 0.0314685314685315];
	MessageFramePosition = [0.218781218781219 0.0262237762237762 0.615384615384615 0.11013986013986];
	ActionsFramePosition = [0.848151848151848 0.0262237762237762 0.138861138861139 0.951048951048951];
	VariablesListboxPosition = [0.240759240759241 0.368881118881119 0.274725274725275 0.5];
	VariablesTextPosition = [0.313686313686314 0.902097902097902 0.127872127872128 0.0314685314685315];
	ViewButtonPosition = [0.244755244755245 0.213286713286713 0.0799200799200799 0.0402097902097902];
	ClearButtonPosition = [0.337662337662338 0.215034965034965 0.0799200799200799 0.0402097902097902];
	SaveButtonPosition = [0.431568431568432 0.213286713286713 0.0799200799200799 0.0402097902097902];
	FileButtonPosition = [0.548451548451548 0.213286713286713 0.11988011988012 0.0402097902097902];
	WorkspaceButtonPosition = [0.689310689310689 0.215034965034965 0.11988011988012 0.0402097902097902];
	MessageTextPosition = [0.232767232767233 0.0646853146853147 0.0669430569430569 0.027972027972028];
	MessageEditPosition = [0.303706293706294 0.0576923076923077 0.433556443556444 0.0402097902097902];
	EraseButtonPosition = [0.746253746253746 0.0576923076923077 0.0799200799200799 0.0402097902097902];
	CustomizeButtonPosition = [0.867132867132867 0.722027972027972 0.0999000999000999 0.0594405594405594];
	HelpButtonPosition = [0.867132867132867 0.592657342657343 0.0999000999000999 0.0594405594405594];
	DemosButtonPosition = [0.867132867132867 0.45979020979021 0.0999000999000999 0.0594405594405594];
	QuitButtonPosition = [0.867132867132867 0.0594405594405594 0.0999000999000999 0.0594405594405594];
	DetailsTextBackgroundColor = frac_color;
	VariablesTextBackgroundColor = frac_color;
	MessageTextBackgroundColor = frac_color;
    FileText = 'File';
    
case 4
	%Layout Mirror
	LogoAxesPosition = [0.04 0.0433333333333333 0.12 0.81];
	MainFramePosition = [0 0 1e-10 1e-10];
	ImportFramePosition  = [0 0 1e-10 1e-10];
	ImportFrameTextPosition  = [0 0 1e-10 1e-10];
	VariableFramePosition = [0 0 1e-10 1e-10];
	VariableFrameTextPosition = [0 0 1e-10 1e-10];
	DetailsListboxPosition = [0.62375 0.533333333333333 0.325 0.38];
	DetailsTextPosition = [0.725 0.933333333333334 0.1275 0.0316666666666667];
	MessageFramePosition = [0 0 1e-10 1e-10];
	ActionsFramePosition = [0 0 1e-10 1e-10];
	VariablesListboxPosition = [0.22125 0.533333333333333 0.325 0.38];
	VariablesTextPosition = [0.32 0.933333333333334 0.1275 0.0316666666666667];
	
	ClearButtonPosition = [0.80625 0.44 0.15375 0.045];
	SaveButtonPosition = [0.60625 0.44 0.15375 0.045];
	FileButtonPosition = [0.41 0.44 0.15375 0.045];
	WorkspaceButtonPosition = [0.21625 0.44 0.15375 0.045];
	
	MessageTextPosition = [0.2225 0.185 0.09125 0.0266666666666667];
	MessageEditPosition = [0.3275 0.176666666666667 0.5275 0.045];
	EraseButtonPosition = [0.80625+0.07 0.176666666666667 0.15375-0.07 0.045];
	
	CustomizeButtonPosition = [0.80625 0.33 0.15375 0.045];
	DemosButtonPosition = [0.41 0.33 0.15375 0.045];
	ViewButtonPosition = [0.21625 0.33 0.15375 0.045];
	HelpButtonPosition = [0.60625 0.33 0.15375 0.045];
	
	QuitButtonPosition = [0.80625+0.07 0.05 0.15375-0.07 0.045];
	
	
	bgsize = size(bg_frac);
	if sum(bgsize)
		dimension = size(bgsize);
		DetailsTextBGPosition = floor(bgsize(1:2).*([1-DetailsTextPosition(2) DetailsTextPosition(1)]));
		VariablesTextBGPosition = floor(bgsize(1:2).*([1-VariablesTextPosition(2) VariablesTextPosition(1)]));
		MessageTextBGPosition = floor(bgsize(1:2).*([1-MessageTextPosition(2) MessageTextPosition(1)]));
		if dimension(2) == 3
			DetailsTextBackgroundColor = 1/255*double(bg_frac(DetailsTextBGPosition(1),DetailsTextBGPosition(2),:));
			VariablesTextBackgroundColor = 1/255*double(bg_frac(VariablesTextBGPosition(1),VariablesTextBGPosition(2),:));
			MessageTextBackgroundColor = 1/255*double(bg_frac(MessageTextBGPosition(1),MessageTextBGPosition(2),:));
		else
			DetailsTextBackgroundColor = bg_cmap_frac(bg_frac(DetailsTextBGPosition(1),DetailsTextBGPosition(2))+1,:);
			VariablesTextBackgroundColor = bg_cmap_frac(bg_frac(VariablesTextBGPosition(1),VariablesTextBGPosition(2))+1,:);
			MessageTextBackgroundColor = bg_cmap_frac(bg_frac(MessageTextBGPosition(1),MessageTextBGPosition(2))+1,:);
		end
		
	else
		DetailsTextBackgroundColor = frac_color;
		VariablesTextBackgroundColor = frac_color;
		MessageTextBackgroundColor = frac_color;		
	end

    FileText = 'Load';

case 5
	%Layout Circle
	LogoAxesPosition = [0.01375 0.0433333333333333 0.1225 0.901666666666667];
	MainFramePosition = [0 0 1e-10 1e-10];
	ImportFramePosition  = [0 0 1e-10 1e-10];
	ImportFrameTextPosition  = [0 0 1e-10 1e-10];
	VariableFramePosition = [0 0 1e-10 1e-10];
	VariableFrameTextPosition = [0 0 1e-10 1e-10];
	DetailsListboxPosition = [0.64375 0.503333333333333 0.325 0.4];
	DetailsTextPosition = [0.745 0.923333333333334 0.1275 0.0316666666666667];
	MessageFramePosition = [0 0 1e-10 1e-10];
	ActionsFramePosition = [0 0 1e-10 1e-10];
	VariablesListboxPosition = [0.27125 0.503333333333333 0.325 0.4];
	VariablesTextPosition = [0.37 0.923333333333334 0.1275 0.0316666666666667];
	
	ClearButtonPosition = [0.82625 0.39 0.15375 0.045];
	SaveButtonPosition = [0.63625 0.39 0.15375 0.045];
	FileButtonPosition = [0.45 0.39 0.15375 0.045];
	WorkspaceButtonPosition = [0.26625 0.39 0.15375 0.045];
	
	MessageTextPosition = [0.205 0.275 0.08125 0.0266666666666667];
	MessageEditPosition = [0.3075 0.266666666666667 0.5775 0.045];
	EraseButtonPosition = [0.82625+0.07 0.266666666666667 0.15375-0.07 0.045];
	
	CustomizeButtonPosition = [0.82625 0.15 0.15375 0.045];
	DemosButtonPosition = [0.45 0.15 0.15375 0.045];
	ViewButtonPosition = [0.26625 0.15 0.15375 0.045];
	HelpButtonPosition = [0.63625 0.15 0.15375 0.045];
	
	QuitButtonPosition = [0.79625+0.07 0.03 0.15375-0.07 0.045];
	DetailsTextBackgroundColor = frac_color;
	VariablesTextBackgroundColor = frac_color;
	MessageTextBackgroundColor = frac_color;

    FileText = 'Load';
    
end



ShowHiddenHandlesInit = get(0,'ShowHiddenHandles');
set(0,'ShowHiddenHandles','on');
fraclabhandle=findobj('Tag','FRACLAB Toolbox');
set(0,'ShowHiddenHandles',ShowHiddenHandlesInit);

if ~isempty(fraclabhandle)
    if strcmp(varargin,'RefreshLayout')
    	axes_frac = findobj(fraclabhandle,'Tag','Axes1');
	logosize = fl_getOption('LogoSize');
	if sum(logosize)
		set(axes_frac,'XLim',[1 logosize(2)]);
		set(axes_frac,'YLim',[1 logosize(1)]);
	end
	image_frac = findobj(fraclabhandle,'Tag','Image1');
	[logo_frac cmap_frac alpha_frac]=fl_getOption('Logo');
	set(image_frac,'CData',logo_frac);
	set(image_frac,'AlphaData',alpha_frac);
	
	axes_frac = findobj(fraclabhandle,'Tag','Axes2');
	bgsize = fl_getOption('BackGroundSize');
	if sum(bgsize)
		set(axes_frac,'XLim',[1 bgsize(2)]);
		set(axes_frac,'YLim',[1 bgsize(1)]);
	end
	image_frac = findobj(fraclabhandle,'Tag','Image2');
	set(image_frac,'CData',fl_getOption('BackGround'));
	
	set(findobj(fraclabhandle,'Tag','Axes1'),'Position',LogoAxesPosition);
	set(findobj(fraclabhandle,'Tag','Frame_List'),'Position',MainFramePosition);
	set(findobj(fraclabhandle,'Tag','frame8'),'Position',ImportFramePosition);
	set(findobj(fraclabhandle,'Tag','text2'),'Position',ImportFrameTextPosition);
	set(findobj(fraclabhandle,'Tag','frame11'),'Position',VariableFramePosition);
	set(findobj(fraclabhandle,'Tag','text4'),'Position',VariableFrameTextPosition);
	set(findobj(fraclabhandle,'Tag','Listbox_details'),'Position',DetailsListboxPosition);
	set(findobj(fraclabhandle,'Tag','StaticText_Details'),'Position',DetailsTextPosition);
	set(findobj(fraclabhandle,'Tag','Frame_Message'),'Position',MessageFramePosition);
	set(findobj(fraclabhandle,'Tag','frame7'),'Position',ActionsFramePosition);
	set(findobj(fraclabhandle,'Tag','Listbox_variables'),'Position',VariablesListboxPosition);
	set(findobj(fraclabhandle,'Tag','StaticText_Variables'),'Position',VariablesTextPosition);
	set(findobj(fraclabhandle,'Tag','Pushbutton_inview'),'Position',ViewButtonPosition);
	set(findobj(fraclabhandle,'Tag','Pushbutton_inclear'),'Position',ClearButtonPosition);
	set(findobj(fraclabhandle,'Tag','Pushbutton_insave'),'Position',SaveButtonPosition);
	set(findobj(fraclabhandle,'Tag','Pushbutton_inload'),'Position',FileButtonPosition);
	set(findobj(fraclabhandle,'Tag','Pushbutton_scanwks'),'Position',WorkspaceButtonPosition);
	set(findobj(fraclabhandle,'Tag','StaticText_mes_error'),'Position',MessageTextPosition);
	set(findobj(fraclabhandle,'Tag','StaticText_error'),'Position',MessageEditPosition);
	set(findobj(fraclabhandle,'Tag','Pushbutton_erase_error'),'Position',EraseButtonPosition);
	set(findobj(fraclabhandle,'Tag','Customize_Button'),'Position',CustomizeButtonPosition);
	set(findobj(fraclabhandle,'Tag','Pushbutton_help'),'Position',HelpButtonPosition);
	set(findobj(fraclabhandle,'Tag','Pushbutton_tuto'),'Position',DemosButtonPosition);
	set(findobj(fraclabhandle,'Tag','Quit_Button'),'Position',QuitButtonPosition);
	
	set(findobj(fraclabhandle,'Tag','StaticText_Details'),'BackgroundColor',DetailsTextBackgroundColor);
	set(findobj(fraclabhandle,'Tag','StaticText_Variables'),'BackgroundColor',VariablesTextBackgroundColor);
	set(findobj(fraclabhandle,'Tag','StaticText_mes_error'),'BackgroundColor',MessageTextBackgroundColor);
    
	set(findobj(fraclabhandle,'Tag','Pushbutton_inload'),'String',FileText);

	switch(fl_getOption('Layout'))
	case 1
		ratio34 = 1.1;
	case 2
		ratio34 = 0.8;
	case 3
		ratio34 = 0.65;
	case 4
		ratio34 = 0.75;
	case 5
		ratio34 = 0.8;				
	end
	
	FigurePosition = get(fraclabhandle,'Position');
	FigurePosition(4) = ratio34*FigurePosition(3);
	set(fraclabhandle,'Position',FigurePosition);
	
	if fl_getOption('Layout') == 4
		set(findobj(fraclabhandle,'Tag','StaticText_Details'),'ForegroundColor',MessageTextBackgroundColor);
		set(findobj(fraclabhandle,'Tag','StaticText_Variables'),'ForegroundColor',MessageTextBackgroundColor);
	end
	

	
    else
    	figure(fraclabhandle);
    	disp('Fraclab 2.0 is already started');
    end
    return
end


WindowsScreenSize = get(0,'ScreenSize');
if fl_getOption('SavePosition')
	frac_position = fl_getOption('FracLabPosition');
else
	frac_position = [0.35*WindowsScreenSize(3) 0.30*WindowsScreenSize(4) 640 690];
end


% h1 = figure(...
% 'Units','normalized',...
% 'PaperUnits',get(0,'defaultfigurePaperUnits'),...
% 'Color',[0.925490196078431 0.913725490196078 0.847058823529412],...
% 'Colormap',jet(0),...
% 'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
% 'MenuBar','none',...
% 'Name','Fraclab_essai',...
% 'PaperPosition',[0.6345175 6.345175 20.30456 15.22842],...
% 'PaperSize',[20.98404194812 29.67743169791],...
% 'PaperType',get(0,'defaultfigurePaperType'),...
% 'Position',[0.5087890625 0.151041666666667 0.5 0.779947916666667],...
% 'HandleVisibility','callback',...
% 'Tag','FRACLAB Toolbox');
% 


h1 = figure('Color',fl_getOption('BackGroundColor'), ...
	'colormap',cmap_frac, ...
	'HandleVisibility','callback', ...
	'MenuBar','none', ...
	'CloseRequestFcn','fl_function(''close_all'');', ...
   'Name','FRACLAB Toolbox', ...
   'Units','pixels', ...
	'Position',frac_position, ...
	'Tag','FRACLAB Toolbox');

a=h1;

h2 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Position',MainFramePosition ,...
'Style','frame',...
'Tag','Frame_List');

h3 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'Callback','fl_clearerror;fl_details;',...
'Position',VariablesListboxPosition,...
'Style','listbox',...
'BackgroundColor',fl_getOption('Fill_inColor'),...
'Tag','Listbox_variables');

h4 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Position',VariableFramePosition,...
'Style','frame',...
'Tag','frame11');

h5 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Position',ImportFramePosition,...
'Style','frame',...
'Tag','frame8');

h6 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Position',ActionsFramePosition,...
'Style','frame',...
'Tag','frame7');

h7 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Position',MessageFramePosition,...
'Style','frame',...
'Tag','Frame_Message');

h13 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',MessageTextBackgroundColor,...
'FontSize',12,...
'FontWeight','bold',...
'HorizontalAlignment','left',...
'Position',MessageTextPosition,...
'String','Message',...
'Style','text',...
'Tag','StaticText_mes_error');

h14 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',fl_getOption('Fill_inColor'),...
'FontUnits','pixels',...
'Enable','inactive',...
'FontSize',12,...
'FontWeight','bold',...
'Position',MessageEditPosition,...
'Style','edit',...
'Tag','StaticText_error');

h15 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback','fl_function(''erase_error'');',...
'FontWeight','bold',...
'FontSize',12,...
'Position',EraseButtonPosition,...
'String','Erase',...
'Tag','Pushbutton_erase_error');

h16 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback','demo toolbox fraclab',...
'FontSize',12,...
'FontWeight','bold',...
'Position',DemosButtonPosition,...
'String','Demos',...
'Tag','Pushbutton_tuto');

h17 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback','doc fraclab_product_page;',...
'FontSize',12,...
'FontWeight','bold',...
'Position',HelpButtonPosition,...
'String','Help',...
'Tag','Pushbutton_help');

h18 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback','fl_callwindow(''gui_view_toolbar'',''gui_view_toolbar'');',...
'FontSize',12,...
'FontWeight','bold',...
'Position',ViewButtonPosition,...
'String','View',...
'Tag','Pushbutton_inview');

h19 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback','fl_function(''mn_save_file'');',...
'FontSize',12,...
'FontWeight','bold',...
'Position',SaveButtonPosition,...
'String','Save',...
'Tag','Pushbutton_insave');

h20 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback','fl_function(''mn_load_file'');',...
'FontSize',12,...
'FontWeight','bold',...
'Position',FileButtonPosition,...
'String',FileText,...
'Tag','Pushbutton_inload',...
'UserData',[]);

h21 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback','eval([''clear '' fl_function(''clear'',0)]);',...
'FontSize',12,...
'FontWeight','bold',...
'Position',ClearButtonPosition,...
'String','Clear',...
'Tag','Pushbutton_inclear');

h22 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback','fl_function(''mn_scanwks'',whos);',...
'FontSize',12,...
'FontWeight','bold',...
'Position',WorkspaceButtonPosition,...
'String','Workspace',...
'Tag','Pushbutton_scanwks',...
'UserData',[]);

h23 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',fl_getOption('Fill_inColor'),...
'Position',DetailsListboxPosition,...
'Style','listbox',...
'Tag','Listbox_details');

h24 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',DetailsTextBackgroundColor,...
'FontSize',12,...
'FontWeight','bold',...
'Position',DetailsTextPosition,...
'String','Details',...
'Style','text',...
'Tag','StaticText_Details');

h25 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',VariablesTextBackgroundColor,...
'FontSize',12,...
'FontWeight','bold',...
'Position',VariablesTextPosition,...
'String','Variables',...
'Style','text',...
'Tag','StaticText_Variables');

h26 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',fl_getOption('FrameColor'),...
'FontSize',12,...
'FontWeight','bold',...
'Position',ImportFrameTextPosition,...
'String','Import data from :',...
'Style','text',...
'Tag','text2');

h27 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',fl_getOption('FrameColor'),...
'FontWeight','bold',...
'FontSize',12,...
'Position',VariableFrameTextPosition,...
'String','Variable :',...
'Style','text',...
'Tag','text4');

h185 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback','fl_callwindow(''Fig_gui_fl_options'',''gui_fl_options'') ;', ...	
'FontSize',12,...
'FontWeight','bold',...
'Position',CustomizeButtonPosition,...
'String','Customize',...
'Tag','Customize_Button');

h186 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback','fl_function(''close_all'');',...
'FontSize',12,...
'FontWeight','bold',...
'Position',QuitButtonPosition,...
'String','Quit',...
'Tag','Quit_Button');

b = axes('Parent',a, ...
	'Units','normalized', ...
	'Position',[0 0 1 1], ...
	'Tag','Axes2',...
	'YDir','reverse', ...
	'Visible','off');
c = image('Parent',b, ...
	'CData',bg_frac, ...
	'Interruptible','off', ...
	'Tag','Image2');%'ButtonDownFcn','helpwin aidegen', ...	

bgsize = fl_getOption('BackGroundSize');
if sum(bgsize)
	set(b,'XLim',[1 bgsize(2)]);
	set(b,'YLim',[1 bgsize(1)]);
end		


b = axes('Parent',a, ...
	'Layer','top', ...
	'Units','normalized', ...
	'Position',LogoAxesPosition, ...
	'Tag','Axes1', ...
	'Layer','top',...
	'YDir','reverse', ...
	'Visible','off');
c = image('Parent',b, ...
	'CData',logo_frac, ...
	'AlphaData', alpha_frac,...
	'Interruptible','off', ...
	'Tag','Image1');%'ButtonDownFcn','helpwin aidegen', ...


logosize = fl_getOption('LogoSize');
if sum(logosize)
	set(b,'XLim',[1 logosize(2)]);
	set(b,'YLim',[1 logosize(1)]);
end		

	
% b = axes('Parent',a, ...
% 	'Box','on', ...
% 	'CameraUpVector',[0 1 0], ...
% 	'CameraUpVectorMode','manual', ...
% 	'Color',[1 1 1], ...
% 	'HandleVisibility','callback', ...
% 	'Layer','top', ...
% 	'Units','normalized', ...
% 	'Position',[0 0 1 1], ...
% 	'Tag','Axes1', ...
% 	'Visible','off', ...
% 	'XColor',[0 0 0], ...
% 	'XLim',[1 1000], ...
% 	'XLimMode','manual', ...
% 	'YColor',[0 0 0], ...
% 	'YDir','reverse', ...
% 	'YLim',[1 1000], ...
% 	'YLimMode','manual', ...
% 	'ZColor',[0 0 0]);
% c = image('Parent',b, ...
% 	'CData',logo_frac, ...
% 	'Interruptible','off', ...
% 	'Tag','Image1');

%%%%%%%%%%% SYNTHESE %%%%%%%%%%%
b = uimenu('Parent',a, ...
	'Label','Synthesis', ...
	'Tag','Synthesis');

c = uimenu('Parent',b, ...
	'Label','Functions', ...
	'Tag','Functions');
d = uimenu('Parent',c, ...
	'Label','Stochastic', ...
	'Tag','Stochastic');
e = uimenu('Parent',d, ...
	'Label','fBm', ...
	'Tag','fBm');
f = uimenu('Parent',e, ...
	'Label','1D', ...
	'Tag','fbm1D');

g = uimenu('Parent',f, ...
	'Callback','fl_callwindow(''Fig_gui_fl_fbm_WoodChan'',''gui_fl_fbm_WoodChan'');', ...
	'Label','fBm (Wood and Chan)', ...
	'Tag','fBm (Wood and Chan)');

g = uimenu('Parent',f, ...
	'Callback','fl_callwindow(''Fig_gui_fl_fbm_Levinson'',''gui_fl_fbm_Levinson'');', ...
	'Label','fBm (Levinson)', ...
	'Tag','fBm (Levinson)');

f = uimenu('Parent',e, ...
	'Label','2D', ...
	'Tag','fbm2D');

g = uimenu('Parent',f, ...
	'Callback','fl_function(''syf_stinc2d'');', ...
	'Label','2D fBm', ...
	'Tag','2D fBm');

e = uimenu('Parent',d, ...
	'Label','mBm', ...
	'Tag','mBm');

f = uimenu('Parent',e, ...
	'Label','1D', ...
	'Tag','mbm1D');

g = uimenu('Parent',f, ...
	'Callback','fl_callwindow(''Fig_gui_fl_mbm_WoodChan'',''gui_fl_mbm_WoodChan'');', ...
	'Label','mBm (improved Wood and Chan)', ...
	'Tag','mBm (improved Wood and Chan)');

g = uimenu('Parent',f, ...
	'Callback','fl_callwindow(''Fig_gui_fl_mbm_Levinson'',''gui_fl_mbm_Levinson'');', ...
	'Label','mBm (Levinson)', ...
	'Tag','mBm (Levinson)');


f = uimenu('Parent',e, ...
	'Label','2D', ...
	'Tag','mbm2D');

g = uimenu('Parent',f, ...
	'Callback','fl_function(''syf_mBm2d'');', ...
	'Label','2D mBm', ...
	'Tag','2D mBm'); 

e = uimenu('Parent',d, ...
	'Callback','fl_callwindow(''Fig_gui_fl_ebp'',''gui_fl_ebp'');', ...
	'Label','EBP', ...
	'Tag','ebp');


e = uimenu('Parent',d, ...
	'Callback','fl_function(''syf_fbmfwt'');', ...
	'Label','Wavelet based 1/f process', ...
	'Tag','Wavelet based 1/f process');       
e = uimenu('Parent',d, ...
	'Callback','fl_callwindow(''Fig_gui_fl_lacunary'',''gui_fl_lacunary'');', ...
	'Label','Lacunary Sequence', ...
	'Tag','lacunary');    
e = uimenu('Parent',d, ...
	'Callback','fl_callwindow(''Fig_gui_fl_stable_syn'',''gui_fl_stable_syn'');', ...
	'Label','Stable Motion', ...
	'Tag','Stable Motion');
e = uimenu('Parent',d, ...
	'Callback','fl_callwindow(''Fig_gui_fl_gifs'',''gui_fl_gifs'');', ...
	'Label','SGIFS', ...
	'Tag','SGIFS');
e = uimenu('Parent',d, ...
	'Callback','fl_function(''syf_swei'');', ...
	'Label','Weierstrass', ...
	'Tag','Weierstrass');
e = uimenu('Parent',d, ...
	'Callback','fl_function(''syf_sgwei'');', ...
	'Label','Generalized Weierstrass', ...
	'Tag','Generalized Weierstrass');
% e = uimenu('Parent',d, ...
% 	'Callback','fl_function(''syf_stinc2d'');', ...
% 	'Label','2D Stationary Increments', ...
% 	'Tag','2D Stationary Increments');    
d = uimenu('Parent',c, ...
	'Label','Deterministic', ...
	'Tag','Deterministic');
e = uimenu('Parent',d, ...
	'Callback','fl_callwindow(''Fig_gui_fl_ifs'',''gui_fl_ifs'');', ...
	'Label','IFS', ...
	'Tag','IFS');
e = uimenu('Parent',d, ...
	'Callback','fl_callwindow(''Fig_gui_fl_prescalpha'',''gui_fl_prescalpha'');', ...
	'Label','GIFS', ...
	'Tag','GIFS');
e = uimenu('Parent',d, ...
	'Callback','fl_function(''syf_dwei'');', ...
	'Label','Weierstrass', ...
	'Tag','Weierstrass');
e = uimenu('Parent',d, ...
	'Callback','fl_function(''syf_dgwei'');', ...
	'Label','Generalized Weierstrass', ...
	'Tag','Generalized Weierstrass');
c = uimenu('Parent',b, ...
	'Label','Measures', ...
	'Tag','Measures');
d = uimenu('Parent',c, ...
	'Label','Multinomial Measures', ...
	'Callback','fl_mms(''deterministic'');', ...
	'Tag','Measures');
d = uimenu('Parent',c, ...
	'Label','Generalized Riesz Product', ...
	'Callback','fl_callwindow(''Fig_gui_fl_riesz'',''gui_fl_riesz'');', ...
	'Tag','Riesz');
% c = uimenu('Parent',b, ...
% 	'Label','Measures', ...
% 	'Callback','fl_mms(''deterministic'');', ...
% 	'Tag','Measures');
% d = uimenu('Parent',c, ...
%       'Callback','fl_mms(''deterministic'');', ...
% 	'Label','Deterministic', ...
%	'Tag','M_Deterministic');
%d = uimenu('Parent',c, ...
%        'Callback','fl_mms(''stochastic'');', ...
%	'Label','Stochastic', ...
%	'Tag','M_Stochastic');


c = uimenu('Parent',b, ...
	'Label','Diffusion-Limited Aggregation', ...
	'Callback','fl_callwindow(''Fig_gui_fl_dla'',''gui_fl_dla'');', ...
	'Tag','dla');
c = uimenu('Parent',b, ...
	'Label','Percolation', ...
	'Callback','fl_callwindow(''Fig_gui_fl_percolation'',''gui_fl_percolation'');', ...
	'Tag','percolation');




c = uimenu('Parent',b, ...
	'Label','Tutorial on Synthesis', ...
    'Separator','on', ...
	'Callback',';', ...
	'Tag','tutorial_synth');
c = uimenu('Parent',b, ...
	'Label','Help on Synthesis', ...
    'Separator','on', ...
	'Callback','doc help_synthesis;', ...
	'Tag','help_synth');





%%%%%%%%%%% FRACTAL DIMENSION %%%%%%%%%%%
b = uimenu('Parent',a, ...
	'Label','Dimensions', ...
	'Tag','Fractal Dimension');

c = uimenu('Parent',b, ...
	'Callback','fl_dimR_init', ...
	'Label','Regularization dimension', ...
	'Tag','Regularization dimension');  

c = uimenu('Parent',b, ...
	 'Label','Box dimension : Box method', ...
	'Tag','Box dimension : Box method');

d = uimenu('Parent',c, ...
         'Callback','fl_boxdim_init(''Signal'')', ...
	 'Label','Signal or grayscale image', ...
	'Tag','SBD');

d = uimenu('Parent',c, ...
         'Callback','fl_boxdim_init(''Binary'')', ...
	 'Label','Binary data', ...
	'Tag','BBD');

d = uimenu('Parent',c, ...
         'Callback','fl_boxdim_init(''List'')', ...
	 'Label','List of points', ...
	'Tag','GBD');


  
% c = uimenu('Parent',b, ...
%          'Callback','fl_boxdim_classic_init', ...
% 	 'Label','Box dimension : Box method', ...
% 	'Tag','Box dimention : Box method');
c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_boxdimvariation'',''gui_fl_boxdimvariation'');', ...
	'Label','Box dimension : Variation method', ...
	'Tag','Box dimension : Variation method');
% c = uimenu('Parent',b, ...
% 	'Callback','fl_warning(''Not implemented yet: choose another'');', ...
% 	'Label','Chemical dimension', ...
% 	'Tag','Chemical dimension');
c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_lac'',''gui_fl_lac'');', ...
	'Label','Lacunarity', ...
	'Tag','Lacunarity');
    
    
    c = uimenu('Parent',b, ...
	'Label','Tutorial on Fractional Dimensions', ...
    'Separator','on', ...
	'Callback',';', ...
	'Tag','tutorial_dim');
c = uimenu('Parent',b, ...
	'Label','Help on Fractional Dimensions', ...
    'Separator','on', ...
	'Callback','doc help_fdim;', ...
	'Tag','help_dim');
    
    
%%%%%%%%%%% EXPONENTS ESTIMATION %%%%%%%%%%%
b = uimenu('Parent',a, ...
	'Label','Exponents', ...
	'Tag','Estimation');

c = uimenu('Parent',b, ...
	'Label','1D Exponents Estimation', ...
	'Tag','Estimation1D');

d = uimenu('Parent',b, ...
	'Label','2D Exponents Estimation', ...
	'Tag','Estimation2D');
	
  %%1D%%
    % %%%% Pointwise   
e = uimenu('Parent',c, ...
	'Label','Pointwise  Holder Exponent', ...
	'Tag','Pointwise Holder Exponent');

    % %%%% Parametric
% f = uimenu('Parent',e, ...
% 	'Label','Parametric estimation', ...
% 	'Callback','fl_callwindow(''gui_estimerH_control_panel'',''gui_estimerH'') ;', ...	
% 	'Tag','Parametric Estimation');
f = uimenu('Parent',e, ...
	'Label','Parametric GQV based estimation', ...
	'Callback','fl_callwindow(''Fig_gui_fl_estimGQV1DH'',''gui_fl_estimGQV1DH'') ;', ...	
	'Tag','Parametric Estimation GQV 1D');


f = uimenu('Parent',e, ...
	'Callback','fl_callwindow(''Fig_gui_fl_osc3'',''gui_fl_osc3'') ;', ...
	'Label','Oscillation based method', ...
	'Tag','1-D  oscillation based estimation');

f = uimenu('Parent',e, ...
	'Callback','fl_callwindow(''Fig_gui_fl_track'',''gui_fl_track'') ;', ...
	'Label','CWT based estimation', ...
   'Tag','CWT based estimation');
f = uimenu('Parent',e, ...
	'Callback','fl_callwindow(''Fig_gui_fl_DWTestim'',''gui_fl_DWTestim'') ;', ...
	'Label','DWT based estimation', ...
	'Tag','DWT based estimation');


f = uimenu('Parent',e, ...
	'Callback','fl_alphagifs_adv_compute(''launch'');', ...
	'Label','GIFS based estimation', ...
	'Tag','GIFS based estimation');

%f = uimenu('Parent',e, ...
%	'Callback','fl_callwindow(''Fig_gui_fl_holder2d'',''gui_fl_holder2d'') ;', ...
%	'Label','2-D direct estimation', ...
%	'Tag','2-D direct estimation');
  
% %%%% Local
e = uimenu('Parent',c, ...
	'Label','Local Holder Exponent', ...
	'Tag','Local Holder Exponent');

f = uimenu('Parent',e, ...
	'Callback','fl_callwindow(''Fig_gui_fl_oscL'',''gui_fl_oscL'') ;', ...
	'Label','oscillation based method', ...
	'Tag','1-D oscillation based estimation');
    
    
% %%%% LongRange dependance
e = uimenu('Parent',c, ...
	'Label','Global Scaling Exponent', ...
	'Tag','LRD Exponent');
f = uimenu('Parent',e, ...
	'Callback','fl_callwindow(''Fig_gui_fl_longrange'',''gui_fl_longrange'') ;', ...
	'Label','CWT based estimation', ...
	'Tag','CWT based estimation');
f = uimenu('Parent',e, ...
	'Callback','fl_callwindow(''Fig_gui_fl_estimcrossingtree'',''gui_fl_estimcrossingtree'');', ...
	'Label','Crossing Tree', ...
	'Tag','crossingtree');	
%f = uimenu('Parent',e, ...
%	'Callback','fl_warning(''Not implemented yet: choose another'');', ...
%	'Label','Other methods', ...
%	'Tag','Other methods');
e = uimenu('Parent',c, ...
	'Label','Stable Processes', ...
	'Tag','Stable Processes');
f = uimenu('Parent',e, ...
	'Callback','fl_stable_function(''mn_culloch'');', ...
	'Label','Mc Culloch Method', ...
	'Tag','Mc Culloch Method');
f = uimenu('Parent',e, ...
	'Callback','fl_stable_function(''mn_koutrouvelis'');', ...
	'Label','Koutrouvelis Method', ...
	'Tag','Koutrouvelis Method');
e = uimenu('Parent',c, ...
	'Label','2-microlocal Frontier', ...
	'Tag','2-microlocal Exponent');
f = uimenu('Parent',e, ...
    	'Callback','fl_callwindow(''gui_fl_tml'',''gui_fl_tml'');', ...
	'Label','Oscillation based (1)', ...
	'Tag','Oscillation');
f = uimenu('Parent',e, ...
	'Label','Oscillation based (2)', ...
	'Tag','Oscillation based (2)');
g = uimenu('Parent',f, ...
    	'Callback','fl_callwindow(''gui_fl_ml2frontier'',''gui_fl_ml2frontier'');', ...
	'Label','One point estimation', ...
	'Tag','Oscml2frontier');
g = uimenu('Parent',f, ...
    	'Callback','fl_callwindow(''gui_fl_ml2spectrum'',''gui_fl_ml2spectrum'');', ...
	'Label','Interval estimation', ...
	'Tag','Oscml2spectrum');
%f = uimenu('Parent',e, ...
%        'Callback','fl_warning(''Not implemented Yet: Choose another'');', ...
%	'Label','CWT based estimation', ...
%	'Tag','CWT based estimation');
%f = uimenu('Parent',e, ...
%        'Callback','fl_warning(''Not implemented yet: choose another'');', ...
%	'Label','DWT based method', ...
%	'Tag','DWT based method');
%f = uimenu('Parent',e, ...
%	'Callback','fl_warning(''Not implemented yet: choose another'');', ...
%	'Label','Other methods', ...
%	'Tag','Other methods');

  %%2D%%
    % %%%% Pointwise   
e = uimenu('Parent',d, ...
	'Label','Pointwise  Holder Exponent', ...
	'Tag','Pointwise Holder Exponent');

    % %%%% Parametric
f = uimenu('Parent',e, ...
	'Label','GQV based estimation', ...
	'Callback','fl_callwindow(''Fig_gui_fl_estimGQV2DH'',''gui_fl_estimGQV2DH'') ;', ...	
	'Tag','Parametric Estimation GQV 2D');


c = uimenu('Parent',b, ...
	'Callback','gui_fl_besov;', ...
	'Label','Besov Norms', ...
	'Tag','Besov Norms');



 c = uimenu('Parent',b, ...
	'Label','Tutorial on Exponents Estimation', ...
    'Separator','on', ...
	'Callback',';', ...
	'Tag','tutorial_expo');
c = uimenu('Parent',b, ...
	'Label','Help on Exponents Estimation', ...
    'Separator','on', ...
	'Callback','doc help_1D_exponents;', ...
	'Tag','help_expo');



%%%%%%%%%%% 1D SIGNALS MULTI FRACTAL SPECTRA %%%%%%%%%%%
z = uimenu('Parent',a, ...
	'Label','Multifractal Spectra', ...
	'Tag','Multifractal Spectra');
b = uimenu('Parent',z, ...
	'Label','1D Multifractal Spectra', ...
	'Tag','1D Multifractal Spectra');
c = uimenu('Parent',b, ...
	'Label','Functions', ...
	'Tag','MS_Functions');
d = uimenu('Parent',c, ...
	'Label','Legendre Spectrum', ...
	'Tag','F_Legendre Spectrum');
e = uimenu('Parent',d, ...
        'Callback','fl_dwtspec_compute(''SpecFunc'') ; ', ...
	'Label','DWT based', ...
	'Tag','DWT based');
e = uimenu('Parent',d, ...
        'Callback','fl_cwtspec_compute(''SpecFunc'') ; ', ...
	'Label','CWT based', ...
	'Tag','CWT based');
e = uimenu('Parent',d, ...
	'Label','Box Method', ...
	'Tag','F_Box Method');
f = uimenu('Parent',e, ...
	'Callback','eval([''global '' fl_lse(''fbasic'',who)]);', ...
	'Label','Basic parameters', ...
	'Tag','FLSE_Basic');
%f = uimenu('Parent',e, ...
%	'Callback','fl_lse(''fadvanced'');', ...
%	'Label','Advanced parameters', ...
%	'Tag','FLSE_Advanced'); 
d = uimenu('Parent',c, ...
	'Label','Continuous Large deviation Spectrum', ...
	'Tag','F_Large deviation Spectrum');
e = uimenu('Parent',d, ...
	'Callback','eval([''global '' fl_ldse(''fbasic'',who)]);', ...
	'Label','Basic parameters', ...
	'Tag','FLDSE_Basic');
e = uimenu('Parent',d, ...
	'Callback','fl_ldse(''fadvanced'',who);', ...
	'Label','Advanced parameters', ...
	'Tag','FLDSE_Advanced');    
d = uimenu('Parent',c,...
    'Label','Lim Sup dimension spectrum',...
    'Tag','M_Dimension spectrum');
e = uimenu('Parent',d, ...
	'Callback','eval([''global '' fl_dse(''fbasic'',who)]);', ...
	'Label','Basic parameters', ...
	'Tag','MDSE_Basic');
e = uimenu('Parent',d, ...
	'Callback','fl_dse(''fadvanced'',who);', ...
	'Label','Advanced parameters', ...
	'Tag','MDSE_Advanced');    
c = uimenu('Parent',b, ...
	'Label','Measures', ...
	'Tag','MS_Measures');
d = uimenu('Parent',c, ...
	'Label','Legendre Spectrum', ...
	'Tag','M_Legendre Spectrum');
e = uimenu('Parent',d, ...
        'Callback','fl_dwtspec_compute(''SpecMeas'') ; ', ...
	'Label','DWT based', ...
	'Tag','DWT based');
e = uimenu('Parent',d, ...
        'Callback','fl_cwtspec_compute(''SpecMeas'') ; ', ...
	'Label','CWT based', ...
	'Tag','CWT based');
e = uimenu('Parent',d, ...
	'Label','Box Method', ...
	'Tag','M_Box Method');
f = uimenu('Parent',e, ...
	'Callback','eval([''global '' fl_lse(''mbasic'',who)]);', ...
	'Label','Basic parameters', ...
	'Tag','MLSE_Basic');
%f = uimenu('Parent',e, ...
	%'Callback','eval([''global '' fl_lse(''madvanced'',who)]);', ...
	%'Label','Advanced parameters', ...
	%'Tag','MLSE_Advanced'); 
d = uimenu('Parent',c, ...
	'Label','Continuous Large Deviation Spectrum', ...
	'Tag','M_Large Deviation Spectrum');
e = uimenu('Parent',d, ...
	'Callback','eval([''global '' fl_ldse(''mbasic'',who)]);', ...
	'Label','Basic parameters', ...
	'Tag','MLDSE_Basic');
e = uimenu('Parent',d, ...
	'Callback','fl_ldse(''madvanced'',who);', ...
	'Label','Advanced parameters', ...
	'Tag','MLDSE_Advanced');
% d = uimenu('Parent',c, ...
% 	'Callback','fl_warning(''Not implemented Yet: Choose another'');', ...
% 	'Label','Tricot Spectrum', ...
% 	'Tag','M_Tricot Spectrum');
d = uimenu('Parent',c, ...
	'Callback','fl_warning(''Not implemented Yet: Choose another'');', ...
	'Label','Hausdorff Spectrum', ...
	'Tag','M_Hausdorff Spectrum');
d = uimenu('Parent',c,...
    'Label','Lim sup dimension spectrum',...
    'Tag','M_Dimension spectrum');
e = uimenu('Parent',d, ...
	'Callback','eval([''global '' fl_dse(''mbasic'',who)]);', ...
	'Label','Basic parameters', ...
	'Tag','MDSE_Basic');
e = uimenu('Parent',d, ...
	'Callback','fl_dse(''madvanced'',who);', ...
	'Label','Advanced parameters', ...
	'Tag','MDSE_Advanced');    
%%%%%%%%%% 2D SIGNALS MULTI FRACTAL SPECTRA %%%%%%%%%%%
b = uimenu('Parent',z, ...
	'Label','2D Multifractal Spectra', ...
	'Tag','2D Multifractal Spectra');
c = uimenu('Parent',b, ...
	'Label','Functions', ...
	'Tag','MS_Functions');
d = uimenu('Parent',c, ...
    'Callback','fl_warning(''Not implemented Yet: Choose another'');', ...
	'Label','Continuous Large Deviation Spectrum', ...
	'Tag','F_Large deviation spectrum');
d = uimenu('Parent',c, ...
	'Label','Lim Sup Dimension Spectrum', ...
	'Tag','F_Dimension spectrum');
e = uimenu('Parent',d, ...
	'Callback','eval([''global '' fl_dse2d(''fbasic'',who)]);', ...
	'Label','Basic parameters', ...
	'Tag','MDSE_Basic');
e = uimenu('Parent',d,...
    'Callback','eval([''global '' fl_dse2d(''fadvanced'',who)]);', ...
    'Label','Advanced parameters',...
    'Tag','MDSE_Advanced');
c = uimenu('Parent',b, ...
	'Label','Measures', ...
	'Tag','MS_Measures');
d = uimenu('Parent',c, ...
    'Callback','fl_warning(''Not implemented Yet: Choose another'');', ...
	'Label','Continuous Large Deviation Spectrum', ...
	'Tag','F_Large deviation spectrum');
% e = uimenu('Parent',d, ...
% 	'Callback','fl_warning(''Not implemented Yet: Choose another'');', ...
% 	'Label','Basic parameters', ...
% 	'Tag','MDSE_Basic');
% e = uimenu('Parent',d,...
%     'Callback','fl_warning(''Not implemented Yet: Choose another'');', ...
%     'Label','Advanced parameters',...
%     'Tag','MDSE_Advanced');
d = uimenu('Parent',c, ...
	'Label','Lim sup dimension Spectrum', ...
	'Tag','M_Dimension spectrum');
e = uimenu('Parent',d, ...
	'Callback','eval([''global '' fl_dse2d(''mbasic'',who)]);', ...
	'Label','Basic parameters', ...
	'Tag','MDSE_Basic');
e = uimenu('Parent',d,...
    'Callback','eval([''global '' fl_dse2d(''madvanced'',who)]);', ...
    'Label','Advanced parameters',...
    'Tag','MDSE_Advanced');




 c = uimenu('Parent',z, ...
	'Label','Tutorial on Multifractal Spectra', ...
    'Separator','on', ...
	'Callback',';', ...
	'Tag','tutorial_spec');
c = uimenu('Parent',z, ...
	'Label','Help on Multifractal Spectra', ...
    'Separator','on', ...
	'Callback','doc help_1D_spectra;', ...
	'Tag','help_spec');





%%%%%%%%%%% STABLE MOTION %%%%%%%%%%%    
b = uimenu('Parent',a, ...
	'Label','Stable Motion', ...
	'Tag','Stable Processes');
c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_stable_syn'',''gui_fl_stable_syn'');', ...
	'Label','Synthesis', ...
	'Tag','Synthesis');
c = uimenu('Parent',b, ...
	'Callback','fl_stable_function(''mn_culloch'');', ...
	'Label','Mc Culloch Method for Parameters Estimation', ...
	'Tag','Mc Culloch Method for Parameters Estimation');
c = uimenu('Parent',b, ...
	'Callback','fl_stable_function(''mn_koutrouvelis'');', ...
	'Label','Koutrouvelis Method for Parameters Estimation', ...
	'Tag','Koutrouvelis Method for Parameters Estimation');
c = uimenu('Parent',b, ...
	'Callback','fl_stable_function(''mn_test_stab'');', ...
	'Label','Test of stability', ...
	'Tag','Test of stability');
c = uimenu('Parent',b, ...
	'Callback','fl_warning(''Not implemented yet: choose another'');', ...
	'Label','Spectral Measure Estimation', ...
	'Tag','Spectral Measure Estimation');
c = uimenu('Parent',b, ...
	'Callback','fl_warning(''Not implemented yet: choose another'');', ...
	'Label','Covariation Estimation', ...
	'Tag','Covariation Estimation');


 c = uimenu('Parent',b, ...
	'Label','Tutorial on Stable Motion', ...
    'Separator','on', ...
	'Callback',';', ...
	'Tag','tutorial_stable');
c = uimenu('Parent',b, ...
	'Label','Help on Stable Motion', ...
    'Separator','on', ...
	'Callback','%doc help_stable;', ...
	'Tag','help_stable');

%%%%%%%%%%% SEGMENTATION %%%%%%%%%%%
b = uimenu('Parent',a, ...
	'Label','Segmentation', ...
   'Tag','Segmentation');    
c = uimenu('Parent',b, ...
    	'Callback','fl_wsamod_compute(''launch'');', ...
	'Label','1D signals WSA-based segmentation', ...
	'Tag','WSA Segmentation');
c = uimenu('Parent',b, ...
    	'Callback','fl_callwindow(''gui_segmentation_control_panel'',''gui_segmentation'');', ...
	'Label','Image multifractal segmentation', ...
	'Tag','SpectrumSegmentation');

c = uimenu('Parent',b, ...
	'Label','Tutorial on Segmentation', ...
    'Separator','on', ...
	'Callback',';', ...
	'Tag','tutorial_segmentation');
c = uimenu('Parent',b, ...
	'Label','Help on Segmentation', ...
    'Separator','on', ...
	'Callback','doc help_segmentation;', ...
	'Tag','help_segmentation');

%%%%%%%%%%% DENOISING %%%%%%%%%%%
b = uimenu('Parent',a, ...
	'Label','Denoising', ...
	'Tag','Denoising');
c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_multden2'',''gui_fl_multden2'');', ...
	'Label','Multifractal Pumping', ...
	'Tag','Multifractal Wavelet Pumping');
c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_multden3'',''gui_fl_multden3'');', ...
	'Label','Non Linear Multifractal Pumping', ...
	'Tag','Non Linear Multifractal Wavelet Pumping');
c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_dreg'',''gui_fl_dreg'');', ...
	'Label','Multifractal Denoising (L2 norm)', ...
   'Tag','Multifractal Denoising');
c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_reg'',''gui_fl_reg'');', ...
	'Label','Multifractal Regularization (L2 norm)', ...
   'Tag','Multifractal Regularization');
c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_reglog'',''gui_fl_reglog'');', ...
	'Label','Multifractal Regularization (pseudo Kullback norm)', ...
   'Tag','Multifractal log Regularization');
c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_bayes'',''gui_fl_bayes'');', ...
	'Label','Multifractal Bayesian Denoising', ...
   'Tag','Multifractal Bayesian Denoising');
c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_shrinkden2'',''gui_fl_shrinkden2'');', ...
	'Label','Wavelet Shrinkage', ...
   'Tag','Wavelet Shrinkage');
c = uimenu('Parent',b, ... 
	'Callback','ud = get(findobj(''Tag'',''FRACLAB Toolbox''),''UserData''); ud.Opened_by_fraclab = 1; set(findobj(''Tag'',''FRACLAB Toolbox''),''UserData'',ud);clear(''ud'');fl_callwindow(''Fig_gui_fl_bayes_IAE'',''gui_fl_bayes_IAE(who)'');', ...
	'Label','Interactive Evolutionary Multifractal Bayesian Denoising', ...
   'Tag','Multifractal Bayesian Denoising IAE');


c = uimenu('Parent',b, ...
	'Label','Tutorial on Denoising', ...
    'Separator','on', ...
	'Callback',';', ...
	'Tag','tutorial_den');
c = uimenu('Parent',b, ...
	'Label','Help on Denoising', ...
    'Separator','on', ...
	'Callback','doc help_denoising;', ...
	'Tag','help_den');


%%%%%%%%%%%%%%%%%%%%%%%%%%% INTERPOLATION



b = uimenu('Parent',a, ...
	'Label','Interpolation', ...
	'Tag','interp');


c = uimenu('Parent',b, ...
	'Callback','fl_callwindow(''Fig_gui_fl_interp'',''gui_fl_interp'');', ...
	'Label','Hölderian Interpolation', ...
	'Tag','interp');


 c = uimenu('Parent',b, ...
	'Label','Tutorial on Interpolation', ...
    'Separator','on', ...
	'Callback',';', ...
	'Tag','tutorial_interp');
c = uimenu('Parent',b, ...
	'Label','Help on Interpolation', ...
    'Separator','on', ...
	'Callback','%doc help_interpolation;', ...
	'Tag','help_interp');


    
%%%%%%%%%%% TF/TS %%%%%%%%%%% 
b = uimenu('Parent',a, ...
	'Label','TF / TS', ...
	'Tag','TFTS');
 c = uimenu('Parent',b, ...
 	'Callback','fl_function(''tfts_cwt'');', ...
 	'Label','Continuous WT', ...
 	'Tag','Continuous WT');
c = uimenu('Parent',b, ...
	'Callback','fl_function(''tfts_dwt'');', ...
	'Label','Discrete WT', ...
	'Tag','Discrete WT');
c = uimenu('Parent',b, ...
	'Callback','fl_function(''tfts_paw'');', ...
	'Label','Pseudo Affine Wigner', ...
	'Tag','Pseudo Affine Wigner');


c = uimenu('Parent',b, ...
	'Label','Help on TF/TS', ...
    'Separator','on', ...
	'Callback','doc help_TFTS;', ...
	'Tag','help_TFTS');

%%%%%%%%%%% MISC. %%%%%%%%%%% 
b = uimenu('Parent',a, ...
	'Label','Misc', ...
	'Tag','Misc');
% c = uimenu('Parent',b, ...
% 	'Callback','gui_fl_create_cwt;', ...
% 	'Label','Create cwt  ', ...
% 	'Tag','Create_cwt');
c = uimenu('Parent',b, ...
	'Callback','gui_fl_create_dwt;', ...
	'Label','Create DWT', ...
	'Tag','Create_dwt');
c = uimenu('Parent',b, ...
	'Callback','gui_fl_create_graph;', ...
	'Label','Create Graph  ', ...
	'Tag','Create_graph');
c = uimenu('Parent',b, ...
	'Callback','gui_fl_create_matrix;', ...
	'Label','Create Matrix  ', ...
	'Tag','Create_matrix');
c = uimenu('Parent',b, ...
	'Callback','gui_extract_matrix;', ...
	'Label','Extract Matrix  ', ...
	'Tag','Extract_matrix');
c = uimenu('Parent',b, ...
	'Callback','gui_oper_matrix;', ...
	'Label','Matrix Computation', ...
	'Tag','oper_matrix');


c = uimenu('Parent',b, ...
	'Callback',...
    'fl_callwindow(''Fig_gui_fl_signal2measure'',''gui_fl_signal2measure'');',...
	'Label','Signal to Measure', ...
	'Tag','sig2measure');

c = uimenu('Parent',b, ...
	'Callback',...
    'fl_callwindow(''Fig_gui_fl_normalize'',''gui_fl_normalize'')', ...
	'Label','Normalization', ...
	'Tag','normalization');

c = uimenu('Parent',b, ...
	'Label','Check for update', ...
  'Separator','on', ...
	'Callback',['!start http://www.irccyn.ec-nantes.fr/FracLab/versioncheck.php?version=' frac_version], ...
	'Tag','checkforupdate');

c = uimenu('Parent',b, ...
	'Label','Help on Misc', ...
    'Separator','on', ...
	'Callback','doc help_misc;', ...
	'Tag','help_misc');

% %%%%%%%%%%% HELPS %%%%%%%%%%% 
% b = uimenu('Parent',a, ...
% 	'Label','Help', ...
% 	'Tag','Helps');
% c = uimenu('Parent',b, ...
% 	'Callback','helpwin help_aidegen;', ...
% 	'Label','General');
% c = uimenu('Parent',b, ...
% 	'Callback','helpwin help_1D_exponents;', ...
% 	'Label','1D Exponents');
% c = uimenu('Parent',b, ...
% 	'Callback','helpwin help_1D_spectra;', ...
% 	'Label','1D Spectra');
% c = uimenu('Parent',b, ...
% 	'Callback','helpwin help_denoising;', ...
% 	'Label','Denoising');
% c = uimenu('Parent',b, ...
% 	'Callback','helpwin help_fdim;', ...
% 	'Label','Fractal dimensions');
% c = uimenu('Parent',b, ...
% 	'Callback','helpwin help_segmentation;', ...
% 	'Label','Segmentation');
% c = uimenu('Parent',b, ...
% 	'Callback','helpwin help_synthesis;', ...
% 	'Label','Synthesis');
% c = uimenu('Parent',b, ...
% 	'Callback','helpwin help_stable_motion;', ...
% 	'Label','Stable Motion');
% c = uimenu('Parent',b, ...
% 	'Callback','helpwin help_TFTS;', ...
% 	'Label','TF / TS');
% c = uimenu('Parent',b, ...
% 	'Callback','helpwin help_misc;', ...
% 	'Label','Misc');  


ud = get(a,'UserData');
ud.OpenedWindows = [];
set(a,'UserData',ud);

try
    fl_window_init(a);
catch
    delete(a);
    error('Failure of the Fraclab window initialization. ''\Gui\fltool.mat'' file may be corrupted. Please reinitialize it.');
end
set(findobj(a,'Tag','StaticText_Details'),'BackgroundColor',DetailsTextBackgroundColor);
set(findobj(a,'Tag','StaticText_Variables'),'BackgroundColor',VariablesTextBackgroundColor);
set(findobj(a,'Tag','StaticText_mes_error'),'BackgroundColor',MessageTextBackgroundColor);
if fl_getOption('Layout') == 4
	set(findobj(a,'Tag','StaticText_Details'),'ForegroundColor',MessageTextBackgroundColor);
	set(findobj(a,'Tag','StaticText_Variables'),'ForegroundColor',MessageTextBackgroundColor);
end

