function fig = gui_axes()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.



% MAIN WINDOW
h0 = figure( ...
	'HandleVisibility','callback', ...
	'MenuBar','none', ...
	'Position',[165 5 300 400], ...
	'Units','pixels', ...
	'Tag','gui_axes_control_panel');get(findobj('Tag','gui_axes_control_panel'),'Name');
% TITLE FRAME    
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.339152435453639, ...
	'ListboxTop',0, ...
	'Position',[0.0298754 0.898052 0.947755 0.0884558], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.75, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.142762 0.920001 0.726625 0.04], ...
	'String','Axes Control Panel', ...
	'Style','text', ...
	'Tag','StaticText6');

% FIGURE FRAME    
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.3, ...
	'ListboxTop',0, ...
	'Position',[0.0298754 0.791251 0.947755 0.1], ...
	'Style','frame', ...
	'Tag','Frame_cFigure');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'ListboxTop',0, ...
	'Position',[0.13 0.81425 0.25 0.05], ...
	'String','plot', ...
	'Style','text', ...
	'Tag','StaticText_cFigure');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'HorizontalAlignment','center', ...
	'ListboxTop',0, ...
	'Position',[0.39 0.815 0.4 0.05], ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','EditText_figName');

    
% PARAMS FRAME     
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0444444444444444, ...
	'ListboxTop',0, ...
	'Position',[0.0298754 0.11 0.947755 0.675], ...
	'Style','frame', ...
	'Tag','Frame_params');

% scale    
h1 = uicontrol('Parent',h0, ...
    'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.24, ...
	'ListboxTop',0, ...
	'Position',[0.04632082986976951 0.65 0.9131944444444448 0.125], ...
	'Style','frame', ...
	'Tag','Frame_scale');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.857142857142857, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.3790523690773067 0.735 0.2 0.035], ...
	'String','Scale', ...
	'Style','text', ...
	'Tag','StaticText_scale');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.714285714285714, ...
	'ListboxTop',0, ...
	'Position',[0.2    0.675    0.14    0.042], ...
	'String','type', ...
	'Style','text', ...
	'Tag','StaticText_scaletype');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_axes(''ppm_scale'');', ...
	'FontSize',0.666666666666667, ...
	'ListboxTop',0, ...
	'Max',4, ...
	'Min',1, ...
	'Position',[0.4 0.675 0.34375 0.045], ...
	'String',{'linear','semilog X','semilog Y', 'LogLog'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_scale', ...
	'Value',1);

% range    
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.142857142857143, ...
	'ListboxTop',0, ...
	'Position',[0.04632082986976951 0.435 0.9131944444444448 0.21], ...
	'Style','frame', ...
	'Tag','Frame_range');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.789473684210526, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.3819    0.595    0.2    0.038], ...
	'String','Range', ...
	'Style','text', ...
	'Tag','StaticText_range');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_axes(''edit_range_Xmin'');', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'Position',[0.36    0.505    0.16    0.05], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText_Xmin');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_axes(''edit_range_Xmax'');', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'Position',[0.63    0.505    0.16    0.05], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','EditText_Xmax');
    
h1 = uicontrol('Parent',h0, ...
        'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_axes(''edit_range_Ymin'');', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'Position',[ 0.36 0.45 0.16    0.05], ...
	'String','3', ...
	'Style','edit', ...
	'Tag','EditText_Ymin');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_axes(''edit_range_Ymax'');', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'Position',[0.63    0.45    0.16    0.05], ...
	'String','4', ...
	'Style','edit', ...
	'Tag','EditText_Ymax');
    
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.857142857142857, ...
	'ListboxTop',0, ...
	'Position',[0.3431    0.56    0.2    0.035], ...
	'String','min', ...
	'Style','text', ...
	'Tag','StaticText_min');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.857142857142857, ...
	'ListboxTop',0, ...
	'Position',[0.6161    0.56    0.2    0.035], ...
	'String','max', ...
	'Style','text', ...
	'Tag','StaticText_max');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'Position',[0.07    0.5    0.25    0.05], ...
	'String','X range', ...
	'Style','text', ...
	'Tag','StaticText_X');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.595238095238095, ...
	'ListboxTop',0, ...
	'Position',[0.07    0.445    0.25    0.0504], ...
	'String','Y range', ...
	'Style','text', ...
	'Tag','StaticText_Y');

% ASPECT FRAME 
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0967741935483871, ...
	'ListboxTop',0, ...
	'Position',[0.04632082986976951 0.12 0.9131944444444448 0.31], ...
	'Style','frame', ...
	'Tag','Frame_aspect');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.75, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.3819    0.375    0.2292    0.04], ...
	'String','Aspect', ...
	'Style','text', ...
	'Tag','StaticText_aspect');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.75, ...
	'ListboxTop',0, ...
	'Position',[0.055    0.32    0.11    0.04], ...
	'String','mark', ...
	'Style','text', ...
	'Tag','StaticText_mark');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_axes(''ppm_mark'');', ...
	'FontSize',0.555555555555556, ...
	'ListboxTop',0, ...
	'Max',14, ...
	'Min',1, ...
	'Position',[0.19 0.325 0.3 0.045], ...
	'String',{'none','. point','o circle','x x-mark','+ plus',...
	'* star','s square', 'd diamond', ...
	'v triangle','^ triangle','< triangle','> triangle',...
	'p pentagram','h hexagram'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_mark', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.75, ...
	'ListboxTop',0, ...
	'Position',[0.5    0.32    0.11    0.04], ...
	'String','line', ...
	'Style','text', ...
	'Tag','StaticText_line');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_axes(''ppm_line'');', ...
	'FontSize',0.611111111111111, ...
	'ListboxTop',0, ...
	'Max',5, ...
	'Min',1, ...
	'Position',[0.635 0.325 0.29 0.045], ...
	'String',{'- solid',': dotted','-. dashdot','-- dashed','none'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_line', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'ListboxTop',0, ...
	'Position',[0.055    0.25    0.11    0.045], ...
	'String','color', ...
	'Style','text', ...
	'Tag','StaticText_color');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_axes(''ppm_color'');', ...
	'FontSize',0.666666666666667, ...
	'ListboxTop',0, ...
	'Max',8, ...
	'Min',1, ...
	'Position',[0.19 0.255 0.34375 0.045], ...
	'String',{'yellow','magenta','cyan', 'red','green','blue','white','black'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_color', ...
	'Value',6);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.697674418604651, ...
	'ListboxTop',0, ...
	'Position',[0.595    0.25    0.14    0.043], ...
	'String','width', ...
	'Style','text', ...
	'Tag','StaticText_width');
h1 = uicontrol('Parent',h0, ...
        'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_axes(''edit_width'');', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'Position',[ 0.75 0.245 0.175    0.05], ...
	'String','0.5', ...
	'Style','edit', ...
	'Tag','EditText_width');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'ListboxTop',0, ...
	'Position',[0.17    0.185    0.16    0.045], ...
	'String','red', ...
	'Style','text', ...
	'Tag','StaticText_red');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'ListboxTop',0, ...
	'Position',[0.4    0.185    0.2    0.045], ...
	'String','green', ...
	'Style','text', ...
	'Tag','StaticText_green');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'ListboxTop',0, ...
	'Position',[0.67    0.185    0.16    0.045], ...
	'String','blue', ...
	'Style','text', ...
	'Tag','StaticText_blue');
h1 = uicontrol('Parent',h0, ...
        'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_axes(''edit_red'');', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'Position',[ 0.17 0.135 0.16    0.05], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText_red');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_axes(''edit_green'');', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'Position',[0.42    0.135   0.16    0.05], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText_green'); 
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_axes(''edit_blue'');', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'Position',[0.67    0.135    0.16    0.05], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','EditText_blue');
    
% BUTTONS
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_axes(''apply'');', ...
	'FontSize',0.375, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.1 0.02 0.25 0.08], ...
	'String','Apply', ...
	'Tag','button_apply');    
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_axes(''close'');', ...
	'FontSize',0.375, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.65 0.02 0.25 0.08], ...
	'String','Close', ...
	'Tag','button_close');

fl_window_init(h0);    
    
%if nargout > 0, fig = h0; end



