function fig = gui_view_toolbar()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.


h0 = figure( ...
	'HandleVisibility','callback', ...
	'MenuBar','none', ...
   'Name','View Toolbar', ...
   'Units','normalized', ...
	'Position',[0 0.17 0.15 0.800], ...
	'Tag','gui_view_toolbar', ...
	'UserData',0);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'Position',[0.05 0.8295 0.9 0.161], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.941 0.8 0.04], ...
	'String','Figure', ...
	'Style','text', ...
	'Tag','StaticText_figure');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.91 0.8 0.03], ...
	'String','view in new', ...
	'CallBack','fl_view_toolbar(''View_in_new'');', ...
	'Tag','button_view_in_new');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.875 0.8 0.03], ...
	'String','view', ...
	'CallBack','fl_view_toolbar(''View'');', ... 
	'Enable','off', ...
	'Tag','button_view');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.84 0.8 0.03], ...
	'String','help', ...
	'Callback','helpwin help_view;', ...
	'Tag','button_Help');
% h1 = uicontrol('Parent',h0, ...
% 	'Units','normalized', ...
% 	'Position',[0.1 0.805 0.8 0.03], ...
% 	'String','close all', ...
% 	'Callback','fl_view_toolbar(''Close_all'');', ...
% 	'Tag','button_Close');

% MODE FRAME
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'Position',[0.05 0.655+0.034 0.9 0.13], ...
	'Style','frame', ...
	'Tag','Frame2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.731+0.034 0.8 0.04], ...
	'String','Image mode', ...
	'Style','text', ...
	'Tag','StaticText_mode');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.7+0.034 0.8 0.03], ...
	'String','image control', ...
	'Enable','off', ...
	'CallBack','fl_view_toolbar(''image'')', ...
	'Tag','button_Image_Matrix');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.665+0.034 0.8 0.03], ...
	'String','superpose', ...
	'Style','checkbox', ...
	'Enable','off', ...
	'CallBack','fl_view_toolbar(''superpose_image'');', ...	
	'Tag','Checkbox_superpose');
    
% TOOLBAR FRAME
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'Position',[0.05 0.305 0.9 0.34+0.034], ...
	'Style','frame', ...
	'Tag','Frame3');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.591+0.034 0.8 0.04], ...
	'String','Tools', ...
	'Style','text', ...
	'Tag','StaticText_tools');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.56+0.034 0.8 0.03], ...
	'String','hold', ...
	'Style','checkbox', ...
	'Enable','off', ...
	'CallBack','fl_view_toolbar (''hold'');', ...
	'Tag','Checkbox_hold');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.525+0.034 0.8 0.03], ...
	'String','rotate', ...
	'Style','checkbox', ...
	'Enable','off', ...
	'CallBack','fl_view_toolbar (''rotate'');', ...
	'Tag','Checkbox_rotate');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.49+0.034 0.8 0.03], ...
	'String','zoom', ...
	'Style','checkbox', ...
	'Enable','off', ...
	'CallBack','fl_view_toolbar(''zoom'');', ...	
	'Tag','Checkbox_zoom');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'Position',[0.1 0.45+0.034 0.5 0.03], ...
	'String','Vsplit', ...
	'Enable','off', ...	
	'Style','text', ...
	'Tag','StaticText_Vsplit');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_view_toolbar (''divide'');', ...
	'FontSize',12, ...
	'Position',[0.55 0.455+0.034 0.25 0.03], ...
	'String','1', ...
	'Enable','off', ...
	'Style','edit', ...
	'Tag','EditText_Vsplit');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'FontSize',12, ...
	'Position',[0.1 0.415+0.034 0.5 0.03], ...
	'String','Hsplit', ...
	'Enable','off', ...	
	'Style','text', ...
	'Tag','StaticText_Hsplit');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_view_toolbar (''divide'');', ...
	'FontSize',12, ...
	'Position',[0.55 0.42+0.034 0.25 0.03], ...
	'String','1', ...
	'Enable','off', ...	
	'Style','edit', ...
	'Tag','EditText_Hsplit');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.385+0.034 0.8 0.03], ...
	'Enable','off', ...
	'String','axes control', ...
	'Callback','fl_view_toolbar(''axes'');', ...
	'Tag','button_Axes');   
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.35+0.034 0.8 0.03], ...
	'Enable','off', ...
	'String','print', ...
	'Callback','fl_view_toolbar(''Print'');', ...
	'Tag','button_print');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.315+0.034 0.8 0.03], ...
	'Enable','off', ...
	'String','close figure', ...
	'Callback','fl_view_toolbar(''Close_figure'');', ...
	'Tag','button_close_figure');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Position',[0.1 0.280+0.034 0.8 0.03], ...
	'String','close all', ...
	'Callback','fl_view_toolbar(''Close_all'');', ...
	'Tag','button_Close');


% LIST BOX
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','pixels', ...
	'CallBack','fl_view_toolbar(''click_listbox'');', ...
	'FontSize',12, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[0.075 0.01 0.85 0.29], ...
	'String',' ', ...
	'Style','listbox', ...
	'Tag','Listbox_figures');
	
fl_window_init(h0);	
    
if nargout > 0, fig = h0; end


