function fig = gui_fl_ebp()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

% head of the box
h0 = figure( ...
	'Colormap',[], ...
	'HandleVisibility','callback', ...
	'MenuBar','none', ...
	'Name','Self Similar Embedded Branching Process', ...
	'Position',[20 50 300 250], ...
	'Tag','Fig_gui_fl_ebp');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.3, ...
	'ListboxTop',0, ...
	'Position',[0.0275 0.87 0.9400000000000001 0.12], ...
	'Style','frame', ...
	'Tag','Frameebp');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.55, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.05 0.875 0.9 0.085], ...
	'String','Self Similar Embedded Branching Process', ...
	'Style','text',  ...
	'Tag','StaticTextTitle');

%==========================================================================
% option geometric function or 2-valued
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.08, ...
	'ListboxTop',0, ...
	'Position',[0.0275 0.37 0.9400000000000001 0.49], ...
	'Style','frame', ...
	'Tag','Frame1');

b = uicontrol(...
	'Parent',h0,...
	'Units','normalized',...
	'FontUnits','normalized',...
	'FontSize',0.7,...
	'FontWeight','bold',...
	'Position',[0.152631578947368 0.77 0.6973684210526316 0.06],...
	'String','Offspring and Sampling functions',...
	'Style','text',...
	'Tag','text6');
% geometric
b = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_ebp_compute(''radiobutton_geom'');', ...
	'FontSize',0.6, ...
	'Position',[0.075 0.68  0.4 0.08], ...
	'String','Geometric', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton_geom', ...
	'Value',1);

b = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.57 0.06 0.08], ...
	'String','H', ...
	'Style','text', ...
	'Tag','StaticText_h_geom');
	
	
b = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_ebp_compute(''edittext_h_geom'');', ...
	'Enable','on', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'Max',0.5, ...
	'Position',[0.1 0.57 0.26 0.08], ...
	'String','0.5', ...
	'Style','edit', ...
	'Tag','EditText_h_geom', ...
	'Value',0.5);

b = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_ebp_compute(''slider_inith'')', ...
	'FontSize',0.3, ...
	'ListboxTop',0, ...
	'Position',[0.07 0.46 0.31 0.08], ...
	'Style','slider', ...
	'Tag','Slider_inith', ...
	'Value',0.5);

	
% 2-valued
b = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_ebp_compute(''radiobutton_2valued'');', ...
	'FontSize',0.6, ...
	'Position',[0.555 0.68 0.4 0.08], ...
	'String','2-valued', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton_2valued', ...
	'Value',0);

b = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'HorizontalAlignment','left', ...
	'Enable','off', ...
	'Position',[0.49 0.57 0.06 0.08], ...
	'String','H', ...
	'Style','text', ...
	'Tag','StaticText_h_2valued');

b = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_ebp_compute(''edittext_h_2valued'');', ...
	'Enable','off', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'Max',0.5, ...
	'Position',[0.69 0.57 0.26 0.08], ...
	'String','0.5', ...
	'Style','edit', ...
	'Tag','EditText_h_2valued', ...
	'Value',0.5);
	
	
b = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',1.2*0.3, ...
	'HorizontalAlignment','left', ...
	'Enable','off', ...
	'Position',[0.49 0.44 0.2 0.13], ...
	'String','Maximum variation', ...
	'Style','text', ...
	'Tag','StaticText_k_2valued');

b = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_ebp_compute(''edittext_k_2valued'');', ...
	'Enable','off', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'Max',0.5, ...
	'Position',[0.69 0.46 0.26 0.08], ...
	'String','5', ...
	'Style','edit', ...
	'Tag','EditText_k_2valued', ...
	'Value',5);
	

%==========================================================================
% length and random seed
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.08, ...
	'ListboxTop',0, ...
	'Position',[0.0275 0.1466666666666667 0.9400000000000001 0.215], ...
	'Style','frame', ...
	'Tag','FrameParam');
%'Sample Size'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.55, ...
	'Position',[0.08 0.25 0.2525 0.08], ...
	'String','Sample Size', ...
	'Style','text', 'HorizontalAlignment', 'Left', ...
	'Tag','StaticText_sample');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_ebp_compute(''ppm_sample'');', ...
	'FontSize',0.5, ...
	'ListboxTop',0, ...
	'Max',10, ...
	'Min',1, ...
	'Position',[0.39 0.26 0.3 0.08], ...
	'String',{'8 points', '16 points', '32 points', '64 points', '128 points', '256 points', '512 points', '1024 points', '2048 points', '4096 points'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_ebp_sample', ...
	'Value',6);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_ebp_compute(''edit_sample'');', ...
	'FontSize',0.5, ...
	'ListboxTop',0, ...
	'Position',[0.7 0.26 0.25 0.08], ...
	'String','256', ...
	'Style','edit', ...
	'Tag','EditText_ebp_sample');

%'Random Seed'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','gui_wei_compute(''edit_randstate'')', ...
	'FontSize',0.55, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.16 0.4025 0.08], ...
	'String','Random Seed', ...
	'Style','text', 'HorizontalAlignment', 'Left', ...
	'Tag','StaticText2');

h1 = uicontrol('Parent',h0, ...
 	'Units','normalized', ...
 	'FontUnits','normalized', ...
 	'FontSize',0.5, ...
     'callback','fl_ebp_compute(''randstate_auto'')', ...
 	'ListboxTop',0, ...
 	'Position',[0.39 0.17 0.3 0.08], ...
 	'String','Auto', ...
     'Value',1, ...
 	'Style','checkbox', ...
 	'Tag','randstate_auto');	
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Enable', 'off', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_ebp_compute(''edit_randstate'')', ...
	'FontSize',0.5, ...
	'ListboxTop',0, ...
	'Position',[0.7 0.17 0.25 0.08], ...
	'String','', ...
	'Style','edit', ...
	'Tag','EditText_ebp_randstate');	

%======================= Compute/Help/Cancel ==============================
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_ebp_compute(''compute'',who)]);', ...
	'FontSize',0.45, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.03 0.03 0.275 0.11], ...
	'String','Compute', ...
	'Tag','Pushbutton_ebp_compute');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_ebp_compute(''help'')', ...
	'FontSize',0.45, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.361 0.03 0.275 0.11], ...
	'String','Help', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'ButtonDownFcn','fl_ebp_compute(''help'')', ...
	'Callback','close(gcf);fl_clearerror', ...
	'FontSize',0.45, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.69 0.03 0.275 0.11], ...
	'String','Close', ...
	'Tag','Pushbutton_cancel');		
		

fl_window_init(h0);
	
if nargout > 0, fig = h0; end
