function gui_fl_prescalpha()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
               

a = figure('Units','pixels', ...
	'HandleVisibility','callback', ...
	'MenuBar','none', ...
	'Name','GIFS with prescribed Holder function', ...
	'Position',[20 50 450 400], ...
	'Tag','Fig_gui_fl_prescalpha');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.196078666666666, ...
	'Position',[0.00567228 0.767087 0.985085 0.222018], ...
	'Style','frame', ...
	'Tag','Frame_prescalpha');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.333333333333332, ...
	'FontWeight','bold', ...
	'Position',[0.133929 0.805092 0.736607 0.1260092], ...
	'String','Contruction of Continuous Functions with Prescribed Holder Function using GIFS', ...
	'Style','text', ...
	'Tag','Statictext_prescalpha');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0957854666666664, ...
	'Position',[0.00567228 0.179989 0.985085 0.576416], ...
	'Style','frame', ...
	'Tag','Frame_gui_scale');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.34, ...
	'HorizontalAlignment','center', ...
	'Position',[0.05 0.595 0.2 0.1], ...
	'String','Interpolation points :', ...
	'Style','text', ...
	'Tag','StaticText_prescalpha_interp');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.639999999999998, ...
	'Position',[0.27 0.65 0.2 0.046], ...
	'String','Enter [x1 y1]', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_gifs_compute(''gifs_edittext_interp1'');', ...
	'FontSize',0.595238666666665, ...
	'HorizontalAlignment','left', ...
	'Position',[0.5 0.65 0.13 0.055], ...
	'String','0.0 0.0', ...
	'Style','edit', ...
	'Tag','EditText_gifs_interp1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.639999999999998, ...
	'Position',[0.64 0.65 0.2 0.046], ...
	'String','Enter [x2 y2]', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_gifs_compute(''gifs_edittext_interp2'');', ...
	'FontSize',0.595238666666665, ...
	'HorizontalAlignment','left', ...
	'Position',[0.84 0.65 0.13 0.055], ...
	'String','0.5 1.0', ...
	'Style','edit', ...
	'Tag','EditText_gifs_interp2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.639999999999998, ...
	'Position',[0.27 0.595 0.2 0.046], ...
	'String','Enter [x3 y3]', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_gifs_compute(''gifs_edittext_interp3'');', ...
	'FontSize',0.595238666666665, ...
	'HorizontalAlignment','left', ...
	'Position',[0.5 0.59 0.13 0.055], ...
	'String','1.0 0.0', ...
	'Style','edit', ...
	'Tag','EditText_gifs_interp3');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.34, ...
	'HorizontalAlignment','center', ...
	'Position',[0.05 0.4 0.2 0.1], ...
	'String','Holder function', ...
	'Style','text', ...
	'Tag','StaticText_alphapresc_holder');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_prescalpha_compute(''edittext_holderfunct'')', ...
	'FontSize',0.505050666666665, ...
	'HorizontalAlignment','left', ...
	'Position',[0.29 0.47 0.65 0.06], ...
	'String','0.2*(1-floor(2*t))+0.8*floor(2*t)', ...
	'Style','edit', ...
	'Tag','EditText_holderfunct');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_prescalpha_compute(''ppm_holderfunct'')', ...
	'FontSize',0.555555999999999, ...
	'Max',4, ...
	'Min',1, ...
	'Position',[0.29 0.405 0.65 0.06], ...
	'String',{'piecewise constant', 'h(t) = t', 'h(t) = abs(sin(3*pi*t))', 'user defined'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_holderfunct', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.34, ...
	'HorizontalAlignment','center', ...
	'Position',[0.05 0.25 0.20042 0.1], ...
	'String','Number of iterations', ...
	'Style','text', ...
	'Tag','StaticText_gifs_iter');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_prescalpha_compute( ''gifs_edittext_iter'');', ...
	'FontSize',0.617283999999998, ...
	'Position',[0.29 0.28 0.25 0.06], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','EditText_gifs_iter');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_prescalpha_compute( ''gifs_slider_iter'');', ...
	'FontSize',0.666666666666665, ...
	'Max',20, ...
	'Min',1, ...
	'Position',[0.6 0.28 0.3 0.06], ...
	'Style','slider', ...
	'Tag','Slider_gifs_iter', ...
	'Value',10);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_prescalpha_compute(''gifs_compute'',who)]);', ...
	'FontSize',0.408641333333333, ...
    'FontWeight','bold', ...
	'Position',[0.111607 0.0660092 0.178571 0.08], ...
	'String','Compute', ...
	'Tag','Pushbutton_gifs_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','helpwin gui_fl_prescalpha_help;', ...
	'FontSize',0.408641333333333, ...
	'FontWeight','bold', ...
	'Position',[0.412946 0.0660092 0.178571 0.08], ...
	'String','Help', ...
	'Tag','Pushbutton_gifs_help');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','close(gcf);', ...
	'FontSize',0.408641333333333, ...
    'FontWeight','bold', ...
	'Position',[0.714286 0.0660092 0.178571 0.08], ...
	'String','Close', ...
	'Tag','Pushbutton_gifs_close');

fl_window_init(a);